Repository ita-social-projects/VictoryCenter-Back, pull requests merged in 2025-06, with the labels that each got.

#129 Updated template of project structure
  docs/101-Project-Structure-Initital.md
  docs/102-Validation.md
  docs/103-Localization-Ideas.md
  docs/VC-CMS.png
  docs/vc-uml.png
Labels: documentation

#102 Feature/issue 93
  VictoryCenter/VictoryCenter.BLL/Commands/Categories/Create/CreateCategoryCommand.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Categories/Create/CreateCategoryHandler.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Categories/Delete/DeleteCategoryCommand.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Categories/Delete/DeleteCategoryHandler.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Categories/Update/UpdateCategoryCommand.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Categories/Update/UpdateCategoryHandler.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Test/DeleteTestData/DeleteTestDataHandler.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Test/UpdateTestData/UpdateTestDataHandler.cs
  VictoryCenter/VictoryCenter.BLL/DTOs/Categories/CategoryDto.cs
  VictoryCenter/VictoryCenter.BLL/DTOs/Categories/CreateCategoryDto.cs
  VictoryCenter/VictoryCenter.BLL/DTOs/Categories/UpdateCategoryDto.cs
  VictoryCenter/VictoryCenter.BLL/Mapping/Categories/CategoriesProfile.cs
  VictoryCenter/VictoryCenter.BLL/Queries/Categories/GetAll/GetAllCategoriesHandler.cs
  VictoryCenter/VictoryCenter.BLL/Queries/Categories/GetAll/GetAllCategoriesQuery.cs
  VictoryCenter/VictoryCenter.BLL/Queries/Test/GetTestData/GetTestDataHandler.cs
  VictoryCenter/VictoryCenter.BLL/Validators/Categories/CreateCategoryValidator.cs
  VictoryCenter/VictoryCenter.BLL/Validators/Categories/UpdateCategoryValidator.cs
  VictoryCenter/VictoryCenter.BLL/VictoryCenter.BLL.csproj
  VictoryCenter/VictoryCenter.DAL/Migrations/20250608150930_AddedMissedMigration.Designer.cs
  VictoryCenter/VictoryCenter.DAL/Migrations/20250608150930_AddedMissedMigration.cs
  VictoryCenter/VictoryCenter.DAL/Migrations/VictoryCenterDbContextModelSnapshot.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Interfaces/Base/IRepositoryWrapper.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Interfaces/Categories/ICategoriesRepository.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Options/QueryOptions.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Realizations/Base/RepositoryBase.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Realizations/Base/RepositoryWrapper.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Realizations/Categories/CategoriesRepository.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/Base/IntegrationTestDbFixture.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/Base/SharedIntegrationTestCollection.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/Categories/Create/CreateCategoryTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/Categories/Delete/DeleteCategoryTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/Categories/GetAll/GetAllCategoriesTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/Categories/Update/UpdateCategoryTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/TestControllerTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/MiddlewareTests/ExceptionHandlingMiddlewareTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/MiddlewareTests/RequestResponseLoggingMiddlewareTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/Seeder/CategoriesSeeder/CategoriesDataSeeder.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/Seeder/IntegrationTestsDatabaseSeeder.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/Seeder/TestSeeder/TestDataSeeder.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/TestDatabaseSeeder.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/VictoryCenterWebApplicationFactory.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Categories/CreateCategoryTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Categories/DeleteCategoryTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Categories/GetCategoriesTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Categories/UpdateCategoryTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Test/DeleteTestDataTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Test/GetAllTestDataTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Test/GetTestDataByIdTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Test/UpdateTestDataTests.cs
  VictoryCenter/VictoryCenter.UnitTests/ValidatorsTests/Categories/CreateCategoryValidatorTests.cs
  VictoryCenter/VictoryCenter.UnitTests/ValidatorsTests/Categories/UpdateCategoryValidatorTests.cs
  VictoryCenter/VictoryCenter.WebAPI/Controllers/BaseApiController.cs
  VictoryCenter/VictoryCenter.WebAPI/Controllers/Categories/CategoriesController.cs
  VictoryCenter/VictoryCenter.WebAPI/Extensions/ServicesConfiguration.cs
Labels: admin panel, back-end

#114 Feature/issue 94
  VictoryCenter/VictoryCenter.BLL/Commands/Categories/Delete/DeleteCategoryHandler.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Categories/Update/UpdateCategoryHandler.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Test/DeleteTestData/DeleteTestDataHandler.cs
  VictoryCenter/VictoryCenter.BLL/Commands/Test/UpdateTestData/UpdateTestDataHandler.cs
  VictoryCenter/VictoryCenter.BLL/DTOs/TeamMembers/TeamMemberDto.cs
  VictoryCenter/VictoryCenter.BLL/DTOs/TeamMembers/TeamMembersFilterDto.cs
  VictoryCenter/VictoryCenter.BLL/Mapping/TeamMembers/TeamMembersProfile.cs
  VictoryCenter/VictoryCenter.BLL/Queries/TeamMembers/GetByFilters/GetTeamMembersByFiltersHandler.cs
  VictoryCenter/VictoryCenter.BLL/Queries/TeamMembers/GetByFilters/GetTeamMembersByFiltersQuery.cs
  VictoryCenter/VictoryCenter.BLL/Queries/TeamMembers/GetById/GetTeamMemberByIdHandler.cs
  VictoryCenter/VictoryCenter.BLL/Queries/TeamMembers/GetById/GetTeamMemberByIdQuery.cs
  VictoryCenter/VictoryCenter.BLL/Queries/Test/GetTestData/GetTestDataHandler.cs
  VictoryCenter/VictoryCenter.DAL/Migrations/20250610074421_AddedMissedMigration.Designer.cs
  VictoryCenter/VictoryCenter.DAL/Migrations/20250610074421_AddedMissedMigration.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Interfaces/Base/IRepositoryWrapper.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Interfaces/TeamMembers/ITeamMembersRepository.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Options/QueryOptions.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Realizations/Base/RepositoryBase.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Realizations/Base/RepositoryWrapper.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Realizations/TeamMembers/TeamMembersRepository.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/Categories/Delete/DeleteCategoryTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/TeamMembers/GetById/GetTeamMemberByIdTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/TeamMembers/GetFiltered/GetFilteredTeamMembersTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/TestControllerTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/Seeder/CategoriesSeeder/CategoriesDataSeeder.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/Seeder/IntegrationTestsDatabaseSeeder.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/Seeder/TeamMembersSeeder/TeamMemberSeeder.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/TeamMembers/GetTeamMemberById.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/TeamMembers/GetTeamMembers.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/Test/GetAllTestDataTests.cs
  VictoryCenter/VictoryCenter.WebAPI/Controllers/TeamMembers/TeamMembersController.cs
  docs/101-Project-Structure-Initital.md
Labels: admin panel, back-end

#177 Feature/issue 91 92
  VictoryCenter/VictoryCenter.BLL/Commands/TeamMembers/Delete/DeleteTeamMemberCommand.cs
  VictoryCenter/VictoryCenter.BLL/Commands/TeamMembers/Delete/DeleteTeamMemberHandler.cs
  VictoryCenter/VictoryCenter.BLL/Commands/TeamMembers/Update/UpdateTeamMemberCommand.cs
  VictoryCenter/VictoryCenter.BLL/Commands/TeamMembers/Update/UpdateTeamMemberHandler.cs
  VictoryCenter/VictoryCenter.BLL/DTOs/TeamMembers/UpdateTeamMemberDto.cs
  VictoryCenter/VictoryCenter.BLL/Mapping/TeamMembers/TeamMembersProfile.cs
  VictoryCenter/VictoryCenter.BLL/Validators/TeamMembers/UpdateTeamMemberValidator.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/TeamMembers/Delete/DeleteTeamMemberTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/TeamMembers/Update/UpdateTeamMemberTests.cs
  VictoryCenter/VictoryCenter.IntegrationTests/Utils/Seeder/IntegrationTestsDatabaseSeeder.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/TeamMembers/DeleteTeamMemberTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/TeamMembers/UpdateTeamMemberTests.cs
  VictoryCenter/VictoryCenter.WebAPI/Controllers/TeamMembers/TeamMembersController.cs
  VictoryCenter/VictoryCenter.WebAPI/appsettings.Development.json
  VictoryCenter/VictoryCenter.WebAPI/appsettings.IntegrationTests.json
  VictoryCenter/VictoryCenter.WebAPI/appsettings.json
Labels: admin panel, back-end

#179 Feature/issue 164
  VictoryCenter/VictoryCenter.BLL/Commands/TeamMembers/Reorder/ReorderTeamMembersCommand.cs
  VictoryCenter/VictoryCenter.BLL/Commands/TeamMembers/Reorder/ReorderTeamMembersHandler.cs
  VictoryCenter/VictoryCenter.BLL/DTOs/TeamMembers/ReorderTeamMembersDto.cs
  VictoryCenter/VictoryCenter.BLL/Validators/TeamMembers/ReorderTeamMembersValidator.cs
  VictoryCenter/VictoryCenter.DAL/Repositories/Realizations/Base/RepositoryBase.cs
  VictoryCenter/VictoryCenter.IntegrationTests/ControllerTests/TeamMembers/Reorder/ReorderTeamMemberTests.cs
  VictoryCenter/VictoryCenter.UnitTests/MediatRHandlersTests/TeamMembers/ReorderTeamMembers.cs
  VictoryCenter/VictoryCenter.UnitTests/ValidatorsTests/TeamMembers/ReorderTeamMembersValidatorTests.cs
  VictoryCenter/VictoryCenter.WebAPI/Controllers/TeamMembers/TeamMembersController.cs
Labels: admin panel, back-end

#205 Open telemetry implementation
  VictoryCenter/VictoryCenter.WebAPI/Extensions/OpenTelemetryConfiguration.cs
  VictoryCenter/VictoryCenter.WebAPI/Program.cs
  VictoryCenter/VictoryCenter.WebAPI/VictoryCenter.WebAPI.csproj
  docker-compose.yml
Labels: back-end
